#pragma once

enum PacketType {
	PacketTypeAck = 1,
	PacketTypePing = 2,
	PacketTypePong = 3,
	PacketTypeInfo = 4,
	PacketTypeSearch = 5,
	PacketTypeLogin = 6,
	PacketTypeLoginOK = 7,
	PacketTypeDisconnect = 8,
	PacketTypeReset = 9,

	PacketTypeState = 11,
	PacketTypeErrors = 12,
	PacketTypeSensors = 13,
	PacketTypeInverter = 14,
	PacketTypeAMS = 15,
	PacketTypeAMSCellData = 16,
	PacketTypeLVPack = 17,
	PacketTypeDriverless = 18,
	PacketTypeLogger = 19,
	PacketTypeRES = 20,
	PacketTypeCorrevit = 21,
	PacketTypeIMU = 22,
	PacketTypeEBS = 23,
	PacketTypeFusebox = 24,
	PacketTypeController = 25,
	PacketTypeClock = 26,
    PacketTypeSteeringActuation = 27,
    PacketTypeVehicleState = 28,
	PacketTypeCooling = 29,
	PacketTypeSpeedWedge = 30,
	PacketTypeFault = 31,
	PacketTypeEKF = 32,

	PacketTypeDebug = 41,
	PacketTypeDebugLog = 42,
	PacketTypeDebugProfiler = 43,
	PacketTypeDebugDisplay = 44,
	PacketTypeDebugDVActuation = 45,

	PacketTypeConfig = 51,
	PacketTypeSetConfig = 52,
	PacketTypeSetClock = 53,

    PacketTypeASState = 61,
	PacketTypeASController = 62,
	PacketTypeASSimulation = 63,
	PacketTypeASSimulationReset = 64,
	PacketTypeASEmergency = 65,

	PacketTypeACUState = 71,
	PacketTypeACUCommand = 72,
};
